rootProject.name = "Readme"
include(":app")
include(":core-ui")
include(":domain")
include(":data")
include(":shared")
include(":feature:main")
include(":feature:set-nick-name")
include(":feature:write-feed")
include(":feature:book-search")
include(":core-data")
